<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>FeedCustomizer</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-$(Platform.ToLower())</RuntimeIdentifier>
		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<SelfContained>true</SelfContained>
		<WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<Target Name="CopyFeedProviderToAssets" BeforeTargets="BeforeBuild">
		<PropertyGroup>
			<_FeedProviderPath>$(ProjectDir)Resources\FeedProvider\</_FeedProviderPath>
		</PropertyGroup>

		<RemoveDir Directories="$(ProjectDir)Resources\FeedProvider" />
		<MakeDir Directories="$(ProjectDir)Resources\FeedProvider" />
		
		<MSBuild Projects="$(MSBuildProjectDirectory)\..\FeedProvider\FeedProvider.csproj" Targets="Publish" Properties="Configuration=$(Configuration);Platform=$(Platform);RuntimeIdentifier=$(RuntimeIdentifier);SelfContained=true;PublishAot=true;PublishTrimmed=true;PublishReadyToRun=false;PublishDir=$(_FeedProviderPath)" BuildInParallel="false" />

		<ItemGroup>
			<Content Include="Resources\**">
				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			</Content>
		</ItemGroup>
	</Target>

	<!-- 在 Clean 之后执行，清理FeedProvider文件 -->
	<Target Name="CustomCleanAfter" AfterTargets="Clean">
		<Message Text="执行自定义清理：清理FeedProvider文件" Importance="High" />

		<RemoveDir Directories="$(ProjectDir)Resources\FeedProvider" />
	</Target>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.3.260402-preview2" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
		<PackageReference Include="Microsoft.WindowsAppSDK.Widgets" Version="2.0.5" />
		<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.6" />
		<PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.1.6" />
		<PackageReference Include="Microsoft.WindowsAppSDK.Runtime" Version="2.4.0" />
	</ItemGroup>
	
	<ItemGroup>
	  <Content Update="Assets\AppIcon.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<!-- Publish Properties -->
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">True</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed>true</PublishTrimmed>
		<DefaultLanguage>en-US</DefaultLanguage>
		<SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>False</GenerateTestArtifacts>
		<AppxBundle>Never</AppxBundle>
		<AppxBundlePlatforms>$(Platform)</AppxBundlePlatforms>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
		<PackageCertificateKeyFile>FeedCustomizer_TemporaryKey.pfx</PackageCertificateKeyFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
</Project>
