// <auto-generated />
#pragma warning disable CS0612, CS0618, CS0649
file unsafe class InterfaceInformation : global::System.Runtime.InteropServices.Marshalling.IIUnknownInterfaceType
{
    public static global::System.Guid Iid { get; } = new([1, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 70]);
    public static void** ManagedVirtualMethodTable => (void**)global::System.Runtime.CompilerServices.Unsafe.AsPointer(in InterfaceImplementation.Vtable);
}

[global::System.Runtime.InteropServices.DynamicInterfaceCastableImplementationAttribute]
file unsafe partial interface InterfaceImplementation : global::FeedProvider.Com.IClassFactory
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.ComInterfaceGenerator", "10.0.14.37416")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::FeedProvider.Com.IClassFactory.CreateInstance(nint pUnkOuter, nint riid, nint ppvObject)
    {
        var(__this, __vtable) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::FeedProvider.Com.IClassFactory));
        var __target = ((delegate* unmanaged[MemberFunction]<void*, nint, nint, nint, int> )__vtable[3]);
        {
            int __retVal;
            {
                __retVal = __target(__this, pUnkOuter, riid, ppvObject);
            }

            // NotifyForSuccessfulInvoke - Keep alive any managed objects that need to stay alive across the call.
            global::System.GC.KeepAlive(this);
            return __retVal;
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.ComInterfaceGenerator", "10.0.14.37416")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    int global::FeedProvider.Com.IClassFactory.LockServer(int fLock)
    {
        var(__this, __vtable) = ((global::System.Runtime.InteropServices.Marshalling.IUnmanagedVirtualMethodTableProvider)this).GetVirtualMethodTableInfoForKey(typeof(global::FeedProvider.Com.IClassFactory));
        var __target = ((delegate* unmanaged[MemberFunction]<void*, int, int> )__vtable[4]);
        {
            int __retVal;
            {
                __retVal = __target(__this, fLock);
            }

            // NotifyForSuccessfulInvoke - Keep alive any managed objects that need to stay alive across the call.
            global::System.GC.KeepAlive(this);
            return __retVal;
        }
    }
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_CreateInstance(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, nint pUnkOuter, nint riid, nint ppvObject)
    {
        global::FeedProvider.Com.IClassFactory @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::FeedProvider.Com.IClassFactory>(__this_native);
            __retVal = @this.CreateInstance(pUnkOuter, riid, ppvObject);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvMemberFunction) })]
    internal static int ABI_LockServer(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int fLock)
    {
        global::FeedProvider.Com.IClassFactory @this = default;
        int __retVal = default;
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::FeedProvider.Com.IClassFactory>(__this_native);
            __retVal = @this.LockServer(fLock);
        }
        catch (global::System.Exception __exception)
        {
            __retVal = global::System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }
}

[global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
file unsafe struct InterfaceImplementationVtable
{
    public delegate* unmanaged[MemberFunction]<void*, global::System.Guid*, void**, int> QueryInterface_0;
    public delegate* unmanaged[MemberFunction]<void*, uint> AddRef_1;
    public delegate* unmanaged[MemberFunction]<void*, uint> Release_2;
    public delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, nint, nint, nint, int> CreateInstance_3;
    public delegate* unmanaged[MemberFunction]<global::System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch*, int, int> LockServer_4;
}

file unsafe partial interface InterfaceImplementation
{
    [global::System.Runtime.CompilerServices.FixedAddressValueTypeAttribute]
    public static readonly InterfaceImplementationVtable Vtable;
    static InterfaceImplementation()
    {
        {
            global::System.Runtime.InteropServices.ComWrappers.GetIUnknownImpl(out *(nint*)&((InterfaceImplementationVtable*)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref Vtable))->QueryInterface_0, out *(nint*)&((InterfaceImplementationVtable*)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref Vtable))->AddRef_1, out *(nint*)&((InterfaceImplementationVtable*)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref Vtable))->Release_2);
        }

        {
            Vtable.CreateInstance_3 = &ABI_CreateInstance;
            Vtable.LockServer_4 = &ABI_LockServer;
        }
    }
}

namespace FeedProvider.Com
{
    [global::System.Runtime.InteropServices.Marshalling.IUnknownDerivedAttribute<InterfaceInformation, InterfaceImplementation>]
    internal partial interface IClassFactory
    {
    }
}

namespace FeedProvider.Com
{
    internal partial interface IClassFactory
    {
    }
}